### ISSUE TITLE
Be able to vote after the voting stage has finished

### ISSUE THREAD

**Issue by LukeGarrigan** [LukeGarrigan/planfree.dev#40]
Received a suggestion to allow users the ability to vote after the voting round has happened. I'm not completely sold on the idea yet, but I'll leave this open for discussion.

**Comment by Ruandv** [comment]
Instead of allowing the users to rather vote again would it not be a good idea to maybe implement a Chat functionality? Seen that the whole socket thing is already in place?

**Comment by LukeGarrigan** [comment]
I don't think a chat system is required, most people will be on teams when they're doing this anyway.
